apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# No namespace resource here; we assume it already exists.
namespace: us103-demos
namePrefix: us103-

resources:
  - ../../base
  - ingress.yaml

labels:
  - pairs:
      site: US103
    includeSelectors: true
    includeTemplates: true

commonAnnotations:
  managed-by: kustomize
  maintainer: bryan

images:
  - name: siddharth67/solar-system
    newTag: v3
