version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token: y28g7n.pau0r7mw57fhawg3
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBKzkrbEZvSHdLdmxOdGlVTXhvZFoxakFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qVXdPVEEwTWpJeE1UUTNXaGNOTXpVd09UQXlNakl4TVRRM1dqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQURRN3FsVGx2am10UWt2TXovUld1WURxeEFIMmhSU1F1TXY1Ck92Yk1XTVVxbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRlBjQVEwTUVtT3FScWFPVQp4Rm8rQmNCUWl4UGNNQVVHQXl0bGNBTkJBQVhSNGtHY1Vva0dScWJlMWhoOVhuZDVBdGVsUVo5QTloeU05V1dqCjdPRzNRZDM5T3dHTVA1Y3IrcENqV2pwQktYdElPU2Y5ZkZodlRWMEpONm1xZVFzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJTVBUWTc2TXBrQTRnY3ZhY01xZ2JkK3RIcitzeERQak9JeVpEU0pndW9vcQotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.34.0
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network: {}
    install:
        disk: /dev/xvda
        image: ghcr.io/siderolabs/installer:v1.11.0
        wipe: false
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
    nodeLabels:
        node.kubernetes.io/exclude-from-external-load-balancers: ""
cluster:
    id: Ss3EmVayWHw4wk2Gsr9bjse1FAsj8nRRqqrEUiHxnn4=
    secret: MZdqZidiypqNANdIXOrR/npzB7yiY0rHvV55UWIYJAc=
    controlPlane:
        endpoint: https://bsus103tal-k8m01.k8s.infutable.com:6443
    clusterName: us103-talos01
    network:
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: tidlxp.8rbmbk1i07cn7a23
    secretboxEncryptionSecret: CQbMeCK8d68j0HLPukPCJcN8aCMf3cQzx8zdC4Bcpds=
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVMrZ0F3SUJBZ0lRQlArVDBMNG1rRUQ1MURrMGQvV2c3akFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNRGt3TkRJeU1URTBOMW9YRFRNMU1Ea3dNakl5TVRFMApOMW93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCTEFkMDRBNmdML0g3M3JRVWpCU2VCeWhCb2UrZEtENkx0b092eHlKZklWTmhGZmRTLzA3dzBQbjl6ZUgKOGlaVzAvbUxyamxEb0NDZ0pvOTBxazhYRWVpallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVjZmdKd3ZZNFo4bUtVc2FRb2duUVRYTnVQd2N3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQVByMXhzYi8KdG41ajE3YXZuamNNWnA5UjBSUGgxeDhrS3ZMclg5a1hudGdYQWlFQXI2SHVWRUJyV3hJYVIzc01nbE82KzVvTQo1WFg5TkMwS1liRFVJNWZua1QwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUNpQXlaeUpxWSt3T1NkelpZazlPZHJjenU5dDB1VXN6OFVKS2hjSW42YW9vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFc0IzVGdEcUF2OGZ2ZXRCU01GSjRIS0VHaDc1MG9Qb3UyZzYvSElsOGhVMkVWOTFML1R2RApRK2YzTjRmeUpsYlQrWXV1T1VPZ0lLQW1qM1NxVHhjUjZBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    aggregatorCA:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJYekNDQVFXZ0F3SUJBZ0lRYUhNM1lCUnJna0d3dWlZUFNEOG40ekFLQmdncWhrak9QUVFEQWpBQU1CNFgKRFRJMU1Ea3dOREl5TVRFME4xb1hEVE0xTURrd01qSXlNVEUwTjFvd0FEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCQ09VdUEzeWhyZWY0ZWN0bHpqSjh5MjBEYUY1TkdWMmwrTEdmUUlDQmRmTnVITzRjMkhiCnorYzRkZXNhWXdMODNlTEQ1cW0ydjNFM1JOeEp0dllsWEVPallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWQKQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZApCZ05WSFE0RUZnUVVManpVTjVKYzMxeUhJNXFUclNLRmg3eE8rT2t3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloCkFPRjdCcWI4TDhaeEkrYzNLV1JUVnhUUS94NXJzdktwWE1KSXMwR0hKZVNkQWlCMTc1aEVSQ2owU0xTbHFaUGoKUEZBZEN6dndWVHNtWjcxSUhPd2VJZlI5TVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1KQnJxTmQ3ZzMwTE5zZS9qeVJ3K0twbVBNYTFiTlpENVdGOENNQU5BQ05vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFSTVTNERmS0d0NS9oNXkyWE9NbnpMYlFOb1hrMFpYYVg0c1o5QWdJRjE4MjRjN2h6WWR2UAo1emgxNnhwakF2emQ0c1BtcWJhL2NUZEUzRW0yOWlWY1F3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    serviceAccount:
        key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS1FJQkFBS0NBZ0VBc05iNS90emtZMnQxNzZiYWpqVzVBam1KL1FCU3pTdXlWK21FTCtTMHhQa2lNL09pCmQrMjVpY0ROd05yR3dnRm9tUjk2ck9FWXdtei8vZmJXbVF3bTJIT1A4TUgyeXNVQUErNTJNcmh4Q0U0K3FWL0wKTGVocnpqY1NrbFBuUGpmTG5YaVBhRk14ZUMrZ2Npb0pSSXhOQXhxVVJzdlp4ZGhxcTFlMHR4alJlOHltd0ovbwo4NDJ0elY5VUlvSVBZTWFKNzdleGZxMjZZeS9CSGp5Q085bjhRZm9YclMxSk96OHNKSUYrdzVYalU1RkhGd0hmCmhHeGxEM1hHWnQ1d3RSZXdyRGVvSGFlRHpsOGlQek8rbmNoQUlzN2F4NTdZMjNFTlNGNVZ3Syt5dVRJVHcveEcKU0tzYmFFYzBrRGY0QTNnMUZqZUlScm9acjVMbEF4RjV6S2lQTjZjb0ROdGJjRnZkZWUyRmVhdkdDam1UaDZDMgo4REpPLzcyYmVnWDVMTmZMOThmYjVPUTJFOWs4VWoycEk5eE5qZTFERmhUU3VtOHpuMDRqMkZ2c0pHa1I0RW1RClNQT0JydlRxZld0eGh5VlJZcEhtNmxubXhsVnRXZWRYeVU4YVJHZVZ2U3dpSGNucDRoTHh6cEhsUGhxK2hOL24KZkhRU0dwUU52N2lVY3I2NDlGQ25WblZvcldOZE5hVTIxOGRXcytRNkpNMVhKQXo1byt4WEwzOCs4Yzl4QkRUdApkZWYzZUk3VVNxUWxiRElGWGFJVEpxWlh6VUN3SmljKzBDRHlRK0t4Qjk1ZCtPeUFKSHZXVWpSblJyb0ZmMXpmCkR0S2k0NXQxcURWRXV3MDJ2WTVlQlkxOHR2VTh3MEtMYlBhS0NvZElXMTU5ZXlhSHJKYm8zaThNTUdVQ0F3RUEKQVFLQ0FnQXFIMExVR05TVDgrUlhMY1RRYSs2Q0g2ZUZLcDhPZlBLUnF5OVA0eWZGNVZ2bXlRa3hqT0FOZG0zcwpHcENPWkp5QUlMWHRXUDYzVFJSYTc0RmxXallraDc1SkNFS2JRUHFFZFRnVlU4YWt4bEo1c0xZcVhMclZGMXdtCm03S3dxTVNvNFM4emwrRm9NZHdEWll6b2xZekFpUU81cTFQWG92bWhqNVlkcU4wNUltR3o3ME1qUkdPYVVETXYKdHhBbnFwTHZsUzlEcitqK09FRkZUUDl1ZHpsMWs3Y3hDbUR2cWxmKzZCT0VUZjhraUMzSlJxcHhsZ29xZVJERgpyd1ZrdFZ4aFlTNTd4Y3VKRERNUm4rY3ZHU1JoeGlqcHRLWU4reXRCU2lzZDV4dm9yZ3QwT3ZLWTI1ei9KVHJaCmdXTmpuQzMwK1V4T0lJVCt3N3dtRTNNU016Sk5sM2V2Z0dTQWltUGRtTjhsTmxWQm5WWW9uekxkZnU1SHdHVWoKWHR3NjFCQk0xeDVuNlZ4TllQTDRoY1pSTGdCNHZJWDdIL0JrWVFiVnA1UXdVRmpSSVlsekI0YW1hNUpEQ3FULwpSYTMza2NtVUtjUWdqbkp0ZjdobVg0UDcvcGY2bzgwQmxsMUhwa3Z2U3k1emNkc3ZFN2ZERWdqdlJXV05BOTF6CmtFcE1sQy9LbWpEQ3dCWUxwTFoxUHk2TXRRdndUVmJzcFQ4VUNkRzlaclQvQlBkZ3d5dWVHcHpQd0FDTStQc0wKUDBGQmE1My9pRVZRNmNYaGhiUktmenJNTmsxM1JVeENTRFA5UTZuT2QvUkxieElxMUwxejJJaVZGWFVKQVh6eApxVno2U0FyeHVTZzFEbnU5aGlqTlAxb0NpQ1g4a3M2WDNCb292aVR2TjFZNTd0VDVBUUtDQVFFQTFmWXF3N1AzCml4VHQrRDJUdmo3V1BNajJIQWRxQjRQWEY4Vlg2T3FQcXVFVTc2cXI0UWV1U2IrMktmMWxqMjlZaUlYL21rZEYKUlZMdUptVFRxM0ZJcmVGdCtnWDV3OWVraHJLVVcvc2x1NDZTQ0ZMTXVJb3ZqU3hOekk4ZE01QnRuUXdrSEpPRwpZNWlzT0I5MXJzaElhWWl4L1FSdW42M1pJem5ybzBZU1ZnQ2R2Yks5SFBoZFVWWmdzQlk2NVhFbnRXMEFuUWdOCmVNWml1STNzMkVhN2QzZ0xvV1VManhOaGpwY2duRURGYkppRWk2QjFYMnA0TEJnTndIbzN6NjJSejYrU1R3dlgKQ2FIV3RZSTlibnUrN2hFVUw4dm9KUU8vYkFrb0JrV3cxNExXUzhxdmg3bWhja1BTdDUzaUtDRFNldEg4U3l6Ygo2VVZ1QUp3OFJnUVg1UUtDQVFFQTA1V29FaGhFVUxMbVkwSWJuRzBqS3lXN2ZIcGhGV3Urd1ZMSGhCdXVXVXpHClRaRE9GK1hzdGVWcy9adTlESGM5L3Jjc1o5KzhlaGRLVFAvakhwMXJoN2dQQy9DVFl3eFY5NFV0T3FNOGl5T2cKMFhmT0x0N3NOQTVXNE5UVkI5R2RWUGdXNXZ6TlYvbUh6TDBxWWRQcEYwNWtyYnlxcUh4U3EyTzlyNlpQdE9tNApQV2xEbHBoWkF3K01lSDhsM3lmVjhTTDFib1llaXRzMlBZTTVTZlJ6L3VienM3T0tGMG9ISGlhY2pNU09LSFllCmlzdDFYRzRKYWIzdTV5TGQ2Z0g3ZlQxR0tKVmVwSTd5SWJFL04yenlUWTJhTTNqQUloeU9FeHBya0pHK3N3Rm0KMWd2d3lYbEJMek1xcElHblZwMUtnRTNCaUh5dVdybXFkd1RPd3QwdWdRS0NBUUVBdTNjRS94VldwZEIvdEVuWApnZyt5UyszVDNMa09TR2xXY3loZ0h0NHRaSTN6ZHczMXJLTzdMRGpCMWNhRVRvbERhOUxrSWZ1aUVOeFpkdUJPCnFWOEhTL3BCRHBoZnZ4ell0WUFRQnd0a2d4R21sNDVjZXEvd2UrTytncVU5ODZqdXNYUXF5N0xpUTY5SDdhQjYKenRvQ3dCeVp2bE04emNGWGg4cSt6LzZjSUNoSURTWm5GZFB5aDBxRVNxUWZsRnB4YlQrRkV4RTBKSWJGaG1ncgpoVTlyLzMvNXlMNHN3MzQ2c3VGdEhCcVFIOWIrQXd4aTZtZnh4TWlLZkFOWmxTZkJvdE4xQUxjaUFQbUFrdVg3CkJ5dDdIVUZ2aTNVLy8vWnBxTEhaRkszSkJQcEk0bjFERUVzdnpscm9iQ0wwUFM2TTNEblJzTmdzRWhYWURNYlcKOUkydmxRS0NBUUF0TXRza2dtcVZrcUlFc2lxVHoveWpTdnd5S3pKeUVRSSs2aUFVNkpUbUhyQitBV0VGV2VpbgpNc3VGb2E5UTZtZ2o4WjFhMDBEQUZCbWJPVTZiUzZXYzZJVE9XQ1lrRW82S3diaFh2bWRBa2V2WTAyOElORGJoCkorOEhPSEFKcTQyZ2lSN2JXVVhFZFZtOU11dksyaW9CQUk0aFR4eGx3YWtuVTdkQnZwVm9ZRVVyV1VGRyttU0oKY3RqZkpNcENVWkF5WXZWckZ0dVBiaVM0SDBBdHZEckxTU3JtU0lSSFZWa1A1OCtwZ3BPYnNSLzFKbUY3elVYVgpnTzE0RXNxMUlwZEd1Y0F6Q3pXY2thekg1Y1ZMWWNxaEpvNjZVQ0U3S0Q1eGRrTmtMcjQrSHg2SXV5UkU1ZEkyCjh3YzQvVGx5RjBmREFObEcvdHVBSmdsMFEyS24zZmdCQW9JQkFRQ1NTOXlmMHZ4bEVwTno4S096c2tTT2JKMEEKalNlbWRwanduaTNHTmpueXpXVE8xMFhzMTBpVFZPVUxST1l5Z0RnR1FlY1BvRENHVGNZMXpFQzlNUzRzZVNHUgoxWnVRSGtmUGlENi9Gam9XS3R1a01mWlp3Ukt4NEhLT3h4azM2RThtSllEdEFlZC9ZYkxTM3I2QUpFVXBsQU1iCmI5dXJYOFVEMmxzK1lHdHA4QzZ6VVVWWi96SVJ6UER3eWUweXdXUTVRelYraUpkTm9YREJwMVEvMnNFaUttQlgKSzM4UWM3ZlFvTENrWFIwYVJqelp2dlQ0aTJ2TG9UZVJBdFNIZGZnMS9aa3hhV0Zmc2ttTDhBeTVZZHVsWi9vbgpVT3lkU1dYa3l6VEYrRGk3UFNtc0xTelg2UldwNStiRjAydDc1RSt3T3FjSWwxV2VlckloWXAxQi9lWncKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.34.0
        certSANs:
            - bsus103tal-k8m01.k8s.infutable.com
        disablePodSecurityPolicy: true
        admissionControl:
            - name: PodSecurity
              configuration:
                apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                defaults:
                    audit: restricted
                    audit-version: latest
                    enforce: baseline
                    enforce-version: latest
                    warn: restricted
                    warn-version: latest
                exemptions:
                    namespaces:
                        - kube-system
                    runtimeClasses: []
                    usernames: []
                kind: PodSecurityConfiguration
        auditPolicy:
            apiVersion: audit.k8s.io/v1
            kind: Policy
            rules:
                - level: Metadata
    controllerManager:
        image: registry.k8s.io/kube-controller-manager:v1.34.0
    proxy:
        image: registry.k8s.io/kube-proxy:v1.34.0
    scheduler:
        image: registry.k8s.io/kube-scheduler:v1.34.0
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
    etcd:
        ca:
            crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmVENDQVNTZ0F3SUJBZ0lSQU4vNG9tbHBLVmZlRE56WTZmRXlmek13Q2dZSUtvWkl6ajBFQXdJd0R6RU4KTUFzR0ExVUVDaE1FWlhSalpEQWVGdzB5TlRBNU1EUXlNakV4TkRkYUZ3MHpOVEE1TURJeU1qRXhORGRhTUE4eApEVEFMQmdOVkJBb1RCR1YwWTJRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRc1cwTldXTWlXCjF2dGxHMDNjWFY1VjRJUFMrT1RKdWZBQXV5aUpHdmYyM2VncUozb05tcjRsaytQWUpoQWljeVlubVRLbVZOcTcKd05jZ3ZrRVFIa2ppbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSApBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRk83c21yc2pwMEI4CmFNOUJBMGFLQ0oxdEJYZXVNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJR0pvRUd0eU9VU0xQclA4L1FUbG42UnkKSG0xWkoyekxybEphNDBZUHlWNTFBaUJjOXZ3VENLUTFFeVVmOVBhSVZBa2ZXUk0wVWxZZGdBVE8rb1JkVnpuaAplZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUw2ZDJNSVBtaTRlV0V4ZkVDaWZKSDZ5TGRqaGt5RVJNcnNmU0JPUHVzdDVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFTEZ0RFZsaklsdGI3WlJ0TjNGMWVWZUNEMHZqa3libndBTHNvaVJyMzl0M29LaWQ2RFpxKwpKWlBqMkNZUUluTW1KNWt5cGxUYXU4RFhJTDVCRUI1STRnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
