# kustomization.yaml (new style)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cilium-rendered.yaml

patches:
  - path: patch-cilium-daemonset.yaml
    target:
      kind: DaemonSet
      name: cilium
      namespace: kube-system

