machine:
  network:
    hostname: bsus103tal-k8m01
    interfaces:
      - interface: eth0
        dhcp: false
        addresses: [10.0.2.2/27]
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.2.1
    nameservers: [10.0.1.2, 10.0.1.3]
    searchDomains: [k8s.infutable.com, infutable.com]
  kubelet:
    extraArgs:
      node-ip: 10.0.2.2
    clusterDNS: [10.96.0.10]
cluster:
  clusterName: us103-talos01
  allowSchedulingOnControlPlanes: false
  network:
    cni:
      name: none                    # using Cilium
    dnsDomain: cluster.local
    podSubnets: [10.244.0.0/16]
    serviceSubnets: [10.96.0.0/12]