#  Author:  Bryan Smith
#  date:    11/11/2025
#  us103-talos01 velero kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero

bases:
  - ../../base

patchesStrategicMerge:
  - values.yaml

commonLabels:
  site: us103
  cluster: us103-kubeadm01
  cluster-type: kubeadm