#  below is the netplan yaml after BGP with the new NIC.  
#  Set loose reverse path filtering.

network:
  version: 2
  ethernets:
    eth0:              #  VLAN20 - East/West
      addresses:
        - 10.0.2.5/27
      nameservers:
        addresses: [10.0.1.2, 10.0.1.3]
        search: [ad.infutable.com]
      routes:
        - to: default
          via: 10.0.2.1
    eth1:              # VLAN30 - North/South (BGP)
      addresses:
        - 10.250.3.5/27